import { expect, test } from "@playwright/test";

// /og.png is generated by satori + resvg (src/pages/og.png.ts). It's the most
// failure-prone runtime route and had zero coverage — a satori regression would
// ship a broken social card silently. Under `output: "static"` it's prerendered
// to a file; the dev server (which these e2e tests run against) renders it on
// demand. The satori/resvg deps optimize on the first hit under `astro dev`, so
// allow a short warm-up before asserting.

test("og.png responds 200 with a PNG body", async ({ request }) => {
  await expect
    .poll(async () => (await request.get("/og.png")).status(), {
      timeout: 30_000,
      message: "/og.png should eventually return 200",
    })
    .toBe(200);

  const res = await request.get("/og.png");
  expect(res.status()).toBe(200);
  expect(res.headers()["content-type"]).toContain("image/png");
  // A real render is tens of KB; a truncated/empty body would be far smaller.
  const body = await res.body();
  expect(body.byteLength).toBeGreaterThan(1000);
  // PNG magic number.
  expect(body.subarray(0, 4).toString("hex")).toBe("89504e47");
});
