#!/usr/bin/env tsx
/**
 * Regenerates src/components/index.ts from the folder structure.
 * A "component" is any .astro, .tsx, or .ts file directly inside a
 * src/components/<Name>/ subdirectory, named identically to that folder.
 *
 * Run: pnpm tsx scripts/gen-barrels.ts
 */

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, "..");
const componentsDir = join(root, "src", "components");
const barrelPath = join(componentsDir, "index.ts");

const extensions = [".tsx", ".ts", ".astro"];

function discoverExports(): string[] {
  const entries = readdirSync(componentsDir, { withFileTypes: true });
  const exports: string[] = [];

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory()) continue;

    const dir = join(componentsDir, entry.name);

    for (const ext of extensions) {
      const candidate = join(dir, `${entry.name}${ext}`);
      try {
        statSync(candidate);
        exports.push(`export * from './${entry.name}/${entry.name}';`);
        break;
      } catch {
        // file doesn't exist, try next extension
      }
    }
  }

  return exports;
}

const lines = discoverExports();
const banner = "// AUTO-GENERATED by scripts/gen-barrels.ts — do not edit\n";
const content =
  lines.length > 0
    ? `${banner}${lines.join("\n")}\n`
    : `${banner}// no components yet\n`;

writeFileSync(barrelPath, content, "utf8");
console.log(`Wrote ${barrelPath} (${lines.length} exports)`);
